name: Trigger a process in Control Room

on:
  pull_request:
    branches:
      - main

jobs:
  run-process:
    runs-on: ubuntu-latest
    name: Trigger process
    steps:
      - name: Trigger Control Room process run
        uses: robocorp/action-trigger-process@v1
        with:
          api-key: Lakshmi Triveni G, Write robots
          workspace-id: -645103aa-bff2-4b7b-828c-8f772b74090b
          process-id: 26205
          payload: '{"foo":"bar"}'
          await-complete: true
